---
title: bio-farming
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
name: Horizons
description: Horizons template for Jekyll
paginate: 10
baseurl: ''
