---
title: bio-farming
timezone: UTC
include:
- _redirects
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
name: Horizons
description: Horizons template for Jekyll
paginate: 10
baseurl: 
sass:
  style: compressed
url: https://www.tomorrow.one
langs:
  en:
    lang-fragment: en
    courses-title: Courses
    contact-title: Contact Us
    login-title: Login
    link:
      microbes: beneficial-microbes
      microbes-title: Production of compost tea, beneficial microbes
      pest-diseases: biological-pest-and-disease-control
      pest-diseases-title: Pests & Diseases and Biological Control
      composting: composting-and-biomass-management
      composting-title: Composting + Biomass Management
      cover-crops: cover-crops-and-mulch-management
      cover-crops-title: Cover Crops and Mulch Management
      crop-rotation: crop-rotation-and-tillage
      crop-rotation-title: Crop Rotation and Tillage
      erosion-control: erosion-control
      erosion-control-title: Erosion Control
      impressum: impressum
      impressum-title: Impressum
      terms-and-conditions: terms-and-conditions
      terms-and-conditions-title: Terms and Conditions
      privacy: privacy-policy.pdf
      privacy-title: Privacy
  es:
    lang-fragment: es
    courses-title: Cursos
    contact-title: Contactanos
    login: iniciar sesión
    link:
      microbes: microbios-beneficiosos
      microbes-title: Microbios beneficiosos
      pest-diseases: plagas-y-enfermedades-y-control-biologico
      pest-diseases-title: Plagas y enfermedades y control biológico
      composting: gestion-de-biomasa-y-compostajes
      composting-title: Gestión de biomasa y compostaje
      cover-crops: cultivos-de-cobertura-y-manejo-de-mantillo
      cover-crops-title: Cultivos de cobertura y manejo de mantillo 
      crop-rotation: rotacion-de-cultivos-y-labaranza-de-conservacion
      crop-rotation-title: Rotación de cultivos y labranza de conservación
      erosion-control: la-erosion-y-su-control
      erosion-control-title: Control de la erosión
      impressum: impressum
      impressum-title: Impressum
      terms-and-conditions: terminos-y-condiciones
      terms-and-conditions-title: Términos y Condiciones
      privacy: politica-de-privacidad.pdf
      privacy-title: Política de Privacidad
