---
title: bio-farming
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
include:
- _redirects
name: Horizons
description: Horizons template for Jekyll
paginate: 10
baseurl: 
sass:
  style: compressed
url: https://www.tomorrow.one
placeholder-title: placeholder
langs:
  en:
    lang-fragment: en
    courses-title: Courses
    contact-title: Contact Us
    login-title: Login
    link:
      microbes: beneficial-microbes
      microbes-title: Production of Compost Tea, Beneficial Microbes
      pest-diseases: biological-pest-and-disease-control
      pest-diseases-title: Pests & Diseases & Biological Control
      composting: composting-and-biomass-management
      composting-title: Composting & Biomass Management
      cover-crops: cover-crops-and-mulch-management
      cover-crops-title: Cover Crops & Mulch Management
      crop-rotation: crop-rotation-and-tillage
      crop-rotation-title: Crop Rotation & Tillage
      erosion-control: erosion-control
      erosion-control-title: Erosion and its control
      impressum: impressum
      impressum-title: Impressum
      terms-and-conditions: terms-and-conditions
      terms-and-conditions-title: Terms & Conditions
      privacy: privacy-policy.pdf
      privacy-title: Privacy
    quiz-start-title: Start the Exam
    quiz-btn-title: Start Quiz
    quiz-start-desc: Once you have read all the material carefully start the exam.
    downloads-title: Downloadable Documents
  es:
    lang-fragment: es
    courses-title: Cursos
    contact-title: Contáctanos
    login: iniciar sesión
    link:
      microbes: produccion-de-te-de-compost-microbios-beneficiosos
      microbes-title: Producción de té de compost, microbios beneficiosos
      pest-diseases: plagas-y-enfermedades-y-control-biologico
      pest-diseases-title: Plagas y enfermedades y control biológico
      composting: compostaje-y-manejo-de-la-biomasa
      composting-title: Compostaje y manejo de la biomasa
      cover-crops: cultivos-de-cobertura-y-manejo-de-mantillo
      cover-crops-title: Cultivos de cobertura y manejo de mantillo
      crop-rotation: rotacion-de-cultivos-y-labaranza-de-conservacion
      crop-rotation-title: Rotación de cultivos y labranza de conservación
      erosion-control: la-erosion-y-su-control
      erosion-control-title: La erosión y su control
      impressum: impressum
      impressum-title: Impressum
      terms-and-conditions: terminos-y-condiciones
      terms-and-conditions-title: Términos y Condiciones
      privacy: politica-de-privacidad.pdf
      privacy-title: Política de Privacidad
    quiz-start-title: Empezar el Examen
    quiz-btn-title: Comenzar el examen
    quiz-start-desc: Después de leer todo, comienza el examen.
    downloads-title: Documentos descargables
