---
title: bio-farming
timezone: UTC
include:
- _redirects
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
name: Horizons
description: Horizons template for Jekyll
paginate: 10
baseurl: 
sass:
  style: compressed
url: https://www.tomorrow.one
langs:
  en:
    lang-fragment: en
    courses-title: Courses
    contact-title: Contact Us
    login-title: Login
    link:
      microbes: beneficial-microbes
      microbes-title: Beneificial Microbes
      pest-diseases: biologicial-pests-and-diseases
      pest-diseases-title: Bioological Pest + Disease Control
      composting: composting-and-biomass-management
      composting-title: Composting + Biomass Management
      cover-crops: cover-crops-and-mulch-management
      cover-crops-title: Cover Crops and Mulch Management
      crop-rotation: crop-rotation-and-tillage
      crop-rotation-title: Crop Rotation and Tillage
      erosion-control: erosion-control
      erosion-control-title: Erosion Control
      impressum: impressum
      impressum-title: Impressum
      terms-and-conditions: terms-and-conditions
      terms-and-conditions-title: Terms and Conditions
  es:
    lang-fragment: es
    courses-title: Cursos
    contact-title: Contactanos
    login: iniciar sesión
    link:
      microbes: microbios-beneficiosos
      microbes-title: Microbios beneficiosos
      pest-diseases: plagas-y-enfermedades-y-control-biologico
      pest-diseases-title: Plagas y enfermedades y control biológico
      composting: gestion-de-biomasa-y-compostaje
      composting-title: Gestión de biomasa y compostaje
      cover-crops: cultivos-de-cobertura-y-manejo-de-mantenillo
      cover-crops-title: Cultivos de cobertura y manejo de mantillo 
      crop-rotation: rotatacion-de-cultivos-y-labranza-de-conservacion
      crop-rotation-title: Rotación de cultivos y labranza de conservación
      erosion-control: control-de-erosion
      erosion-control-title: Control de la erosión
      impressum: impressum
      impressum-title: Impressum
      terms-and-conditions: terms-and-conditions
      terms-and-conditions-title: Terms and Conditions
